# $Id: Makefile.win,v 1.4 2007/05/08 20:36:04 carregal Exp $

T= md5
V= 1.0.2

include config.win

OBJS= src\md5.obj src\md5lib.obj 
LUAS= src\md5.lua


.c.obj:
	$(CC) /c /Fo$@ $(CFLAGS) $<

src\$(LIBNAME) : $(OBJS)
	link /dll /def:src\$(T).def /out:src\$(LIBNAME) $(OBJS) $(LUA_LIB)

install: src\$(LIBNAME)
	IF NOT EXIST $(LUA_DIR) mkdir $(LUA_DIR)
	copy src\$(LIBNAME) $(LUA_LIBDIR)	
	copy $(LUAS) $(LUA_DIR)

clean:
	FOR %i in ($(OBJS)) DO del %i
	del src\$(LIBNAME) src\$T.lib src\$T.exp
